version: "2"

services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
    deploy:
      replicas: 3 # Lo mismo que docker compose up --scale web=3

  traefik:
    image: traefik:v2.5
    hostname: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - --log.level=INFO  # Nivel de log para ver más detalles
    ports:
      - "7070:80" # Traefik HTTP entrypoint
      - "7071:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"